# Generated by Django 4.1.4 on 2022-12-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Country')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Article text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Article created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Article updated at')),
                ('published', models.BooleanField(default=True, verbose_name='Article published')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='footballersAPI.country', verbose_name='Country')),
            ],
        ),
    ]
